GET http://localhost:8080/clientes HTTP/1.1

GET http://localhost:8080/clientes/1 HTTP/1.1

GET http://localhost:8080/clientes/pessoa-fisica/ HTTP/1.1

POST http://localhost:8080/clientes/pessoa-fisica/ HTTP/1.1
content-type:"application/json"